name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    permissions:
      contents: read
      packages: write
    uses: LMCustoms/.github/.github/workflows/docker-build-push.yml@main
    with:
      image-name: "lmcustoms/landing"
    secrets: inherit
